---
AWSTemplateFormatVersion: 2010-09-09
Description: >
  A template to spin up an EC2 instance with Erlang and Elixir installed.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network Configuration
      Parameters:
      - VPC
      - AvailabilityZone
      - SubnetId

    - Label:
        default: Amazon EC2 Instance Configuration
      Parameters:
      - InstanceType
      - InstanceKey
      - InstanceSubnet
      - PrimarySecurityGroup
      - SecondarySecurityGroup
      - AssignPublicIP
      - Sudo

    - Label:
        default: SNS EMail
      Parameters:
      - MyEmail

    - Label:
        default: FT Required Tags
      Parameters:
      - TagEnvironment
      - TagTeamDL
      - TagSystemCode
      - TagIpCode
      - TagDescription
      - TagName
      - TagStopSchedule

    ParameterLabels:
      InstanceType:
        default: Instance Type
      InstanceKey:
        default: Instance EC2 User Key
      InstanceSubnet:
        default: Subnet instance is in
      PrimarySecurityGroup:
        default: Primary Security Group
      SecondarySecurityGroup:
        default: Secondary Security Group
      AssignPublicIP:
        default: Require Public IP?
      Sudo:
        Default: The Sudo group to be added

Parameters:
  VPC:
    Description: This is the VPC the stack will be deployed inside.
    Type: AWS::EC2::VPC::Id
    Default: vpc-c9dfd5ab

  PrimarySecurityGroup:
    Description: The primary security group used by ELB, database and instance.
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-4b1f7f2e

  SecondarySecurityGroup:
    Description: The secondary security group used by ELB, database and instance.
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-7cfe9a19

  AvailabilityZone:
    Description: Availability zone install the resources into.
    Type: AWS::EC2::AvailabilityZone::Name
    Default: eu-west-1b

  InstanceSubnet:
    Description: The subnets to assign to the Instance; must match the AZ
    Type: AWS::EC2::Subnet::Id
    Default: subnet-ca6f3b8c

  InstanceType:
    Description: The type and size of the instance. Check documentation for recommended types.
    Type: String
    AllowedValues:
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - m4.4xlarge
    - m4.10xlarge
    - m4.16xlarge
    - m3.medium
    - m3.large
    - m3.xlarge
    - m3.2xlarge
    - c4.large
    - c4.xlarge
    - c4.2xlarge
    - c4.4xlarge
    - c4.8xlarge
    - c3.large
    - c3.xlarge
    - c3.2xlarge
    - c3.4xlarge
    - c3.8xlarge
    - p2.xlarge
    - p2.8xlarge
    - p2.16xlarge
    - g2.2xlarge
    - g2.8xlarge
    - x1.32xlarge
    - r3.large
    - r3.xlarge
    - r3.2xlarge
    - r3.4xlarge
    - r3.8xlarge
    - i2.xlarge
    - i2.2xlarge
    - i2.4xlarge
    - i2.8xlarge
    - d2.xlarge
    - d2.2xlarge
    - d2.4xlarge
    - d2.8xlarge
    Default: t2.small

  InstanceKey:
    Description: EC2User Key
#    Type: AWS::EC2::KeyPair::KeyName
    Type: String

  MyEmail:
    Description: SNS Email Subscription to send alerts to.
    Type: String
    ConstraintDescription: There must be a valid email address for the SNS Topic
    AllowedPattern: ^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$

  Sudo:
    Description: Sudo Group to be applied by default
    Type: String
    Default: sudomemb

  AssignPublicIP:
    Description: Whether you need a public IP. This must be true for public subnets and false for private subnets
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'

  IamInstanceProfile:
    Description: What IAM profile to give to this instance - for future use. Currently has to be FT-Linux-Role
    Type: String
    Default: FT-Linux-Role
    AllowedValues:
      - FT-Linux-Role
      - FTPlatformGateway
      - AnsibleProvisioner

  ImageId:
    Description: The AMI to be used, this MUST be an Amazon Linux image for the userdata to build correctly. A default is given.
    Type: String
    Default: ami-d41d58a7

  TagEnvironment:
    Description: Tag detail for the Environment
    Type: String
    Default: int
    AllowedValues:
      - 'd'
      - 't'
      - 'p'
      - 'int'

  TagTeamDL:
    Description: Tag detail for the TeamDL
    ConstraintDescription: There must be a valid email address for the TeamDL Topic
    Type: String
    AllowedPattern: ^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$
    Default: membership.engineering@ft.com

  TagSystemCode:
    Description: Tag detail for the SystemCode
    Type: String
    Default: Membership

  TagIpCode:
    Description: Tag detail for the ipCode
    Type: String
    Default: P142

  TagDescription:
    Description: Tag detail for the describing the instance.
    Type: String
    Default: Erlang/Elixir Build Node
    AllowedPattern : ([a-zA-Z0-9].*)

  TagName:
    Description: Tag detail for the Name used in the console of the instance. NOT THE HOSTNAME OF THE INSTANCE.
    Type: String
    Default: memb-build-1-eu-p

  TagStopSchedule:
    Description: Tag detail for the when the instance is to be powered off.
    Type: String
    Default: everyday

Conditions:
  HasKeyName:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: InstanceKey

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroupIds:
      - Ref: PrimarySecurityGroup
      - Ref: SecondarySecurityGroup
      SubnetId:
        Ref: InstanceSubnet
      InstanceType:
        Ref: InstanceType
      AvailabilityZone:
        Ref: AvailabilityZone
      ImageId:
        Ref: ImageId
      KeyName:
        Fn::If:
        - HasKeyName
        - Ref: InstanceKey
        - Ref: AWS::NoValue
      IamInstanceProfile:
        Ref: IamInstanceProfile
      Tags:
      - Key: environment
        Value:
          Ref: TagEnvironment
      - Key: teamDL
        Value:
          Ref: TagTeamDL
      - Key: systemCode
        Value:
          Ref: TagSystemCode
      - Key: ipCode
        Value:
          Ref: TagIpCode
      - Key: description
        Value:
          Ref: TagDescription
      - Key: Name
        Value:
          Ref: TagName
      - Key: stopSchedule
        Value:
          Ref: TagStopSchedule
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          /usr/bin/aws s3 cp s3://ft-ce-repository/amazon-ftbase/releases/bootstrap.sh .
          bash ./bootstrap.sh -s ${Sudo} -e ${TagEnvironment}
          # Gist: https://gist.github.com/eikes/e2ce65e8f02e99d54010
          # Dev tools
          sudo yum -y install git
          # Required for Erlang build
          sudo yum -y groupinstall "Development Tools"
          sudo yum -y install openssl-devel ncurses-devel

          # Create build user, and install tools locally under that user:
          sudo adduser build
          sudo su - build

          # ASDF https://github.com/asdf-vm/asdf
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.2.1
          echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bashrc
          echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.bashrc
          . ~/.asdf/asdf.sh
          
          asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
          asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
          asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git

          asdf install erlang 19.2
          asdf global erlang 19.2

          asdf install elixir 1.4.1
          asdf global elixir 1.4.1

          asdf install nodejs 6.9.5
          asdf global nodejs 6.9.5

  InstanceCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: CPU for instance.
      AlarmActions:
      - Ref: SNSTopic
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: '60'
      EvaluationPeriods: '3'
      Threshold: '90'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: MyInstance
        Value:
          Ref: MyInstance

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint:
          Ref: MyEmail
        Protocol: email

Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value:
      Ref: MyInstance
  PrivateIP:
    Description: Private IP address of the newly created EC2 instance
    Value:
      !GetAtt MyInstance.PrivateIp
